#ifndef DRAWING_H
#define DRAWING_H

enum InkEffects {
    INK_NONE,
    INK_BLEND,
    INK_ALPHA,
    INK_ADD,
    INK_SUBTRACT,
    INK_5,
    INK_EQUAL,
    INK_NOTEQUAL,
};

enum DrawFX { FX_NONE, FX_FLIP, FX_ROTATE_NOFLIP, FX_ROTATE, FX_SCALE_NOFLIP, FX_SCALE, FX_ROTOZOOM_NOFLIP, FX_ROTOZOOM };

enum FlipFlags { FLIP_NONE, FLIP_X, FLIP_Y, FLIP_XY };

#endif // !DRAWING_H