name: Build Mania

on:
  push:
    branches:
      - master

env:
  GENERAL_FLAGS: "-DWITH_RSDK=OFF -DCMAKE_BUILD_TYPE=Release"
  V5_FLAGS: "-DRETRO_REVISION=2"
  V5U_FLAGS: "-DRETRO_REVISION=3"
  # Normally you would use $VCPKG_INSTALLATION_PATH, but it's broken...so hardcode C:/vcpkg
  GENERAL_WIN_FLAGS: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
  WIN32_FLAGS: "-DVCPKG_TARGET_TRIPLET=x86-windows-static -A Win32"
  WIN64_FLAGS: "-DVCPKG_TARGET_TRIPLET=x64-windows-static"

jobs:
  mania-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Mania
        run: |
          cmake -B build_v5 ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN32_FLAGS}} ${{env.V5_FLAGS}}
          cmake --build build_v5 --parallel --config Release
          cmake -B build_v5U ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN32_FLAGS}} ${{env.V5U_FLAGS}}
          cmake --build build_v5U --parallel --config Release
      - name: Move artifacts
        run: |
          mkdir artifacts
          mkdir artifacts/v5
          mkdir artifacts/v5U
          mv ./build_v5/Release/*.dll ./artifacts/v5/
          mv ./build_v5U/Release/*.dll ./artifacts/v5U/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mania-windows
          path: artifacts
  mania-windows-x64:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Mania
        run: |
          cmake -B build_v5 ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN64_FLAGS}} ${{env.V5_FLAGS}}
          cmake --build build_v5 --parallel --config Release
          cmake -B build_v5U ${{env.GENERAL_FLAGS}} ${{env.GENERAL_WIN_FLAGS}} ${{env.WIN64_FLAGS}} ${{env.V5U_FLAGS}}
          cmake --build build_v5U --parallel --config Release
      - name: Move artifacts
        run: |
          mkdir artifacts
          mkdir artifacts/v5
          mkdir artifacts/v5U
          mv ./build_v5/Release/*.dll ./artifacts/v5/
          mv ./build_v5U/Release/*.dll ./artifacts/v5U/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mania-windows-x64
          path: artifacts
  mania-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Mania
        run: |
          cmake -B build_v5 ${{env.GENERAL_FLAGS}} ${{env.V5_FLAGS}}
          cmake --build build_v5 --parallel
          cmake -B build_v5U ${{env.GENERAL_FLAGS}} ${{env.V5U_FLAGS}}
          cmake --build build_v5U --parallel
      - name: Move artifacts
        run: |
          mkdir artifacts
          mkdir artifacts/v5
          mkdir artifacts/v5U
          mv ./build_v5/lib*.so ./artifacts/v5/
          mv ./build_v5U/lib*.so ./artifacts/v5U/
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mania-linux
          path: artifacts
